name: Run tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [DOC-123-typesense]





jobs:
  build:
    runs-on: ubuntu-latest

    services:
      typesense:
        image: typesense/typesense:${{ matrix.typesense-version }}

      - name: Create Typesense server
        run: |
          docker run -d \
            --add-host=host.docker.internal:host-gateway \
            -p 8108:8108 \
            --name typesense \
            -v /tmp/typesense:/data \
            typesense/typesense:26.0 \
            --api-key=xyz \
            --data-dir /data \
            --enable-cors
